version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: students
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306